config = {
    "device": 'mps',
    'vocab_size': 10000,
    'context_length': 256,
    'd_model': 512,
    'num_layers': 4,
    'num_heads': 16,
    'd_ff': 1344,
    'rope_theta': 10000,
    'max_lr': 1e-3,
    'min_lr': 1e-6,
    'total_iterations': 80000,
    'warmup_iters': 4000,
    'batch_size': 16,
    'max_grad_norm': 5,
    'save_every': 10000,
    'val_every': 1000,
    'train_data_path': "data/TinyStoriesV2-GPT4-train.txt.tokenized.npy",
    'val_data_path': "data/TinyStoriesV2-GPT4-valid.txt.tokenized.npy",
    'output_root_path': 'models/test'
}